import { Hono } from 'hono';
import { and, desc, eq } from 'drizzle-orm';
import { z } from 'zod';
import { db } from '@/db/client.js';
import { canchas, horarios, reservas } from '@/db/schema.js';
import { requireAuth, requireRole } from '@/shared/auth.js';
import { fail, ok } from '@/shared/response.js';

const createSchema = z.object({ id_horario: z.coerce.number().int().positive(), fecha_reserva: z.string().date(), observaciones: z.string().max(255).optional() });
const statusSchema = z.object({ estado: z.enum(['confirmada', 'rechazada', 'cancelada']) });
const spanishDays = ['domingo', 'lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado'];
function weekday(date: string) { return spanishDays[new Date(`${date}T00:00:00Z`).getUTCDay()]; }
const reservationQuery = () => db.select({ id_reserva: reservas.id, id_solicitante: reservas.idSolicitante, id_horario: reservas.idHorario, fecha_reserva: reservas.fechaReserva, estado: reservas.estado, observaciones: reservas.observaciones, horario: { id: horarios.id, dia_semana: horarios.diaSemana, hora_inicio: horarios.horaInicio, hora_fin: horarios.horaFin }, cancha: { id: canchas.id, nombre: canchas.nombre, tipo_superficie: canchas.tipoSuperficie } }).from(reservas).innerJoin(horarios, eq(reservas.idHorario, horarios.id)).innerJoin(canchas, eq(horarios.idCancha, canchas.id));
const reservationDto = (reservation: typeof reservas.$inferSelect) => ({ id_reserva: reservation.id, id_solicitante: reservation.idSolicitante, id_horario: reservation.idHorario, fecha_reserva: reservation.fechaReserva, estado: reservation.estado, observaciones: reservation.observaciones });
export const reservasRoutes = new Hono();
reservasRoutes.post('/', requireAuth, async (c) => { const auth = c.get('authUser'); if (auth.role !== 'solicitante') return fail(c, 'Solo los solicitantes pueden crear reservas', 403); const parsed = createSchema.safeParse(await c.req.json().catch(() => null)); if (!parsed.success) return fail(c, 'Datos de reserva inválidos', 422, parsed.error.flatten().fieldErrors); const [schedule] = await db.select().from(horarios).where(and(eq(horarios.id, parsed.data.id_horario), eq(horarios.estado, 'disponible'))).limit(1); if (!schedule) return fail(c, 'El horario no está disponible', 409); if (weekday(parsed.data.fecha_reserva) !== schedule.diaSemana) return fail(c, `La fecha seleccionada no corresponde al día ${schedule.diaSemana}`, 422); const conflict = await db.select({ id: reservas.id }).from(reservas).where(and(eq(reservas.idHorario, parsed.data.id_horario), eq(reservas.fechaReserva, parsed.data.fecha_reserva), eq(reservas.estado, 'confirmada'))).limit(1); if (conflict.length) return fail(c, 'El horario ya está reservado para esa fecha', 409); try { const [created] = await db.insert(reservas).values({ idSolicitante: auth.id, idHorario: parsed.data.id_horario, fechaReserva: parsed.data.fecha_reserva, observaciones: parsed.data.observaciones }).returning(); return ok(c, reservationDto(created), 'Reserva creada', 201); } catch { return fail(c, 'No fue posible crear la reserva; puede existir un conflicto', 409); } });
reservasRoutes.get('/mis-reservas', requireAuth, async (c) => { const auth = c.get('authUser'); if (auth.role !== 'solicitante') return fail(c, 'Solo los solicitantes tienen reservas propias', 403); return ok(c, await reservationQuery().where(eq(reservas.idSolicitante, auth.id)).orderBy(desc(reservas.fechaReserva))); });
reservasRoutes.patch('/:id/cancelar', requireAuth, async (c) => { const auth = c.get('authUser'); const id = Number(c.req.param('id')); const condition = auth.role === 'administrador' ? eq(reservas.id, id) : and(eq(reservas.id, id), eq(reservas.idSolicitante, auth.id)); const [updated] = await db.update(reservas).set({ estado: 'cancelada' }).where(condition).returning(); return updated ? ok(c, updated, 'Reserva cancelada') : fail(c, 'Reserva no encontrada o no autorizada', 404); });
reservasRoutes.get('/admin', requireAuth, requireRole('administrador'), async (c) => ok(c, await reservationQuery().orderBy(desc(reservas.fechaReserva))));
reservasRoutes.patch('/admin/:id/estado', requireAuth, requireRole('administrador'), async (c) => { const parsed = statusSchema.safeParse(await c.req.json().catch(() => null)); if (!parsed.success) return fail(c, 'Estado inválido', 422, parsed.error.flatten().fieldErrors); const [updated] = await db.update(reservas).set({ estado: parsed.data.estado }).where(eq(reservas.id, Number(c.req.param('id')))).returning(); return updated ? ok(c, updated, 'Estado de reserva actualizado') : fail(c, 'Reserva no encontrada', 404); });
