import { sql } from 'drizzle-orm';
import { db } from './client.js';

await db.execute(sql`ALTER TABLE solicitantes ADD COLUMN IF NOT EXISTS contrasena VARCHAR(255) DEFAULT '';`);
await db.execute(sql`UPDATE solicitantes SET contrasena = '' WHERE contrasena IS NULL;`);
await db.execute(sql`ALTER TABLE reservas DROP CONSTRAINT IF EXISTS chk_reservas_estado;`);
await db.execute(sql`ALTER TABLE reservas ADD CONSTRAINT chk_reservas_estado CHECK (estado IN ('confirmada', 'rechazada', 'cancelada'));`);
await db.execute(sql`CREATE UNIQUE INDEX IF NOT EXISTS uq_reserva_horario_fecha ON reservas (id_horario, fecha_reserva) WHERE estado <> 'cancelada';`);
await db.execute(sql`ALTER TABLE solicitantes ALTER COLUMN contrasena SET DEFAULT '';`);
await db.execute(sql`ALTER TABLE solicitantes ALTER COLUMN contrasena SET NOT NULL;`);
await db.execute(sql.raw(`
DO $$
DECLARE item record;
BEGIN
  FOR item IN SELECT * FROM (VALUES
    ('administradores', 'id_administrador'),
    ('solicitantes', 'id_solicitante'),
    ('canchas', 'id_cancha'),
    ('horarios', 'id_horario'),
    ('reservas', 'id_reserva')
  ) AS ids(table_name, column_name)
  LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_attribute a
      JOIN pg_class t ON t.oid = a.attrelid
      WHERE t.relname = item.table_name
        AND a.attname = item.column_name
        AND a.attidentity IN ('a', 'd')
    ) THEN
      EXECUTE format('ALTER TABLE %I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY', item.table_name, item.column_name);
    END IF;
  END LOOP;
END $$;`));
console.log('Migraciones del backend aplicadas');
process.exit(0);
