CREATE DATABASE "CampusFICHdb";

\connect "CampusFICHdb"

CREATE TABLE administradores (
    id_administrador INTEGER GENERATED BY DEFAULT AS IDENTITY,
    usuario VARCHAR(50),
    contrasena VARCHAR(255),
    fecha_creacion TIMESTAMP
);

CREATE TABLE solicitantes (
    id_solicitante INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombres VARCHAR(100),
    apellidos VARCHAR(100),
    correo VARCHAR(150),
    contrasena VARCHAR(255),
    tipo_usuario VARCHAR(20),
    codigo_fich VARCHAR(30),
    fecha_registro TIMESTAMP
);

CREATE TABLE canchas (
    id_cancha INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100),
    tipo_superficie VARCHAR(50),
    descripcion VARCHAR(255)
);

CREATE TABLE horarios (
    id_horario INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_cancha INTEGER,
    dia_semana VARCHAR(15),
    hora_inicio TIME,
    hora_fin TIME,
    estado VARCHAR(20),
    fecha_creacion TIMESTAMP
);

CREATE TABLE reservas (
    id_reserva INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_solicitante INTEGER,
    id_horario INTEGER,
    fecha_reserva DATE,
    estado VARCHAR(20),
    observaciones VARCHAR(255),
    fecha_creacion TIMESTAMP
);
